### ISSUE TITLE
3.3.10: configure fails with "cannot compute sizeof (size_t)"

### ISSUE THREAD

**Issue by kloczek** [FFTW/fftw3#260]
auoconf 2.71
```console
+ cd fftw-3.3.10
+ autoreconf -fiv
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
autoreconf: running: /usr/bin/autoconf --force
configure.ac:32: warning: 'AM_CONFIG_HEADER': this macro is obsolete.
configure.ac:32: You should use the 'AC_CONFIG_HEADERS' macro instead.
./lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
aclocal.m4:781: AM_CONFIG_HEADER is expanded from...
configure.ac:32: the top level
configure.ac:48: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:48: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:48: the top level
configure.ac:53: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:53: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:53: the top level
configure.ac:56: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:56: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:56: the top level
configure.ac:62: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:62: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:62: the top level
configure.ac:67: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:67: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:67: the top level
configure.ac:68: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:68: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:68: the top level
configure.ac:78: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:78: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:78: the top level
configure.ac:89: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:89: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:89: the top level
configure.ac:111: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:111: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:111: the top level
configure.ac:118: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:118: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:118: the top level
configure.ac:128: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:128: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:128: the top level
configure.ac:137: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:137: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:137: the top level
configure.ac:146: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:146: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:146: the top level
configure.ac:159: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:159: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:159: the top level
configure.ac:167: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:167: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:167: the top level
configure.ac:176: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:176: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:176: the top level
configure.ac:185: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:185: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:185: the top level
configure.ac:191: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:191: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:191: the top level
configure.ac:206: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:206: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:206: the top level
configure.ac:211: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:211: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:211: the top level
configure.ac:216: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:216: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:216: the top level
configure.ac:221: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:221: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:221: the top level
configure.ac:226: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:226: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:226: the top level
configure.ac:232: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:232: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:232: the top level
configure.ac:249: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:249: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:249: the top level
configure.ac:254: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:254: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:254: the top level
configure.ac:259: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:259: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:259: the top level
configure.ac:260: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:260: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:260: the top level
configure.ac:265: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:265: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:265: the top level
configure.ac:270: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:270: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:270: the top level
configure.ac:273: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:273: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:273: the top level
configure.ac:291: warning: The macro `AC_PROG_CC_STDC' is obsolete.
configure.ac:291: You should run autoupdate.
./lib/autoconf/c.m4:1666: AC_PROG_CC_STDC is expanded from...
configure.ac:291: the top level
configure.ac:295: warning: The macro `AC_LIBTOOL_WIN32_DLL' is obsolete.
configure.ac:295: You should run autoupdate.
m4/ltoptions.m4:148: AC_LIBTOOL_WIN32_DLL is expanded from...
configure.ac:295: the top level
configure.ac:295: warning: AC_LIBTOOL_WIN32_DLL: Remove this warning and the call to _LT_SET_OPTION when you
configure.ac:295: put the 'win32-dll' option into LT_INIT's first parameter.
./lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
m4/ltoptions.m4:148: AC_LIBTOOL_WIN32_DLL is expanded from...
configure.ac:295: the top level
configure.ac:296: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:296: You should run autoupdate.
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:296: the top level
configure.ac:303: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:303: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:303: the top level
configure.ac:309: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:309: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
m4/acx_mpi.m4:37: ACX_MPI is expanded from...
configure.ac:309: the top level
configure.ac:489: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:489: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:489: the top level
configure.ac:510: warning: The macro `AC_HEADER_TIME' is obsolete.
configure.ac:510: You should run autoupdate.
./lib/autoconf/headers.m4:743: AC_HEADER_TIME is expanded from...
configure.ac:510: the top level
configure.ac:579: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:579: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:579: the top level
configure.ac:589: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:589: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:589: the top level
configure.ac:597: warning: The macro `AC_TRY_RUN' is obsolete.
configure.ac:597: You should run autoupdate.
./lib/autoconf/general.m4:2997: AC_TRY_RUN is expanded from...
m4/ax_check_compiler_flags.m4:15: AX_CHECK_COMPILER_FLAGS is expanded from...
m4/ax_gcc_aligns_stack.m4:19: AX_GCC_ALIGNS_STACK is expanded from...
configure.ac:597: the top level
configure.ac:607: warning: The macro `ac_cv_prog_gcc' is obsolete.
configure.ac:607: You should run autoupdate.
./lib/autoconf/c.m4:440: ac_cv_prog_gcc is expanded from...
configure.ac:607: the top level
configure.ac:634: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:634: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:634: the top level
configure.ac:665: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:665: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:665: the top level
configure.ac:672: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:672: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:672: the top level
configure.ac:679: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:679: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1534: AC_ARG_ENABLE is expanded from...
configure.ac:679: the top level
configure.ac:685: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:685: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
./lib/autoconf/general.m4:1553: AC_ARG_WITH is expanded from...
configure.ac:685: the top level
configure.ac:702: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:702: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:702: the top level
configure.ac:710: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:710: You should run autoupdate.
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
m4/acx_pthread.m4:48: ACX_PTHREAD is expanded from...
configure.ac:710: the top level
configure.ac:710: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:710: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
m4/acx_pthread.m4:48: ACX_PTHREAD is expanded from...
configure.ac:710: the top level
configure.ac:731: warning: The macro `AC_TRY_CPP' is obsolete.
configure.ac:731: You should run autoupdate.
./lib/autoconf/general.m4:2762: AC_TRY_CPP is expanded from...
configure.ac:731: the top level
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:288: installing './compile'
configure.ac:31: installing './missing'
api/Makefile.am: installing './depcomp'
support/Makefile.codelets:71: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:64:   'support/Makefile.codelets' included from here
support/Makefile.codelets:72: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:64:   'support/Makefile.codelets' included from here
support/Makefile.codelets:73: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:64:   'support/Makefile.codelets' included from here
support/Makefile.codelets:74: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:64:   'support/Makefile.codelets' included from here
dft/scalar/codelets/Makefile.am:75: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:78: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:81: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:84: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:87: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:90: warning: '%'-style pattern rules are a GNU make extension
dft/scalar/codelets/Makefile.am:93: warning: '%'-style pattern rules are a GNU make extension
support/Makefile.codelets:71: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
support/Makefile.codelets:72: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
support/Makefile.codelets:73: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
support/Makefile.codelets:74: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
dft/simd/common/Makefile.am:21: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:24: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:27: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:30: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:33: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:36: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:39: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:42: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:45: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:48: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:51: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:54: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:57: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:60: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:63: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:66: warning: '%'-style pattern rules are a GNU make extension
dft/simd/common/Makefile.am:69: warning: '%'-style pattern rules are a GNU make extension
mpi/Makefile.am:42: warning: source file '$(top_srcdir)/tests/fftw-bench.c' is in a subdirectory,
mpi/Makefile.am:42: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least one source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However, this
automake: behavior may change in a future Automake major version, with object
automake: files being placed in the same subdirectory as the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
mpi/Makefile.am:42: warning: source file '$(top_srcdir)/tests/hook.c' is in a subdirectory,
mpi/Makefile.am:42: but option 'subdir-objects' is disabled
support/Makefile.codelets:71: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:75:   'support/Makefile.codelets' included from here
support/Makefile.codelets:72: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:75:   'support/Makefile.codelets' included from here
support/Makefile.codelets:73: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:75:   'support/Makefile.codelets' included from here
support/Makefile.codelets:74: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:75:   'support/Makefile.codelets' included from here
rdft/scalar/r2cb/Makefile.am:85: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:88: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:91: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:94: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:97: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:100: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:103: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cb/Makefile.am:106: warning: '%'-style pattern rules are a GNU make extension
support/Makefile.codelets:71: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:75:   'support/Makefile.codelets' included from here
support/Makefile.codelets:72: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:75:   'support/Makefile.codelets' included from here
support/Makefile.codelets:73: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:75:   'support/Makefile.codelets' included from here
support/Makefile.codelets:74: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:75:   'support/Makefile.codelets' included from here
rdft/scalar/r2cf/Makefile.am:85: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:88: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:91: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:94: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:97: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:100: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:103: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2cf/Makefile.am:106: warning: '%'-style pattern rules are a GNU make extension
support/Makefile.codelets:71: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:47:   'support/Makefile.codelets' included from here
support/Makefile.codelets:72: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:47:   'support/Makefile.codelets' included from here
support/Makefile.codelets:73: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:47:   'support/Makefile.codelets' included from here
support/Makefile.codelets:74: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:47:   'support/Makefile.codelets' included from here
rdft/scalar/r2r/Makefile.am:60: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:63: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:66: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:69: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:73: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:76: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:79: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:82: warning: '%'-style pattern rules are a GNU make extension
rdft/scalar/r2r/Makefile.am:86: warning: '%'-style pattern rules are a GNU make extension
support/Makefile.codelets:71: warning: '%'-style pattern rules are a GNU make extension
rdft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
support/Makefile.codelets:72: warning: '%'-style pattern rules are a GNU make extension
rdft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
support/Makefile.codelets:73: warning: '%'-style pattern rules are a GNU make extension
rdft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
support/Makefile.codelets:74: warning: '%'-style pattern rules are a GNU make extension
rdft/simd/common/Makefile.am:13:   'support/Makefile.codelets' included from here
rdft/simd/common/Makefile.am:18: warning: '%'-style pattern rules are a GNU make extension
rdft/simd/common/Makefile.am:21: warning: '%'-style pattern rules are a GNU make extension
autoreconf: Leaving directory '.'
+ export F77=gfortran
+ F77=gfortran
+ BASEFLAGS='--enable-shared --enable-threads'
+ BASEFLAGS+=' --enable-openmp'
+ prec_name[0]=single
+ prec_name[1]=double
+ prec_name[2]=long
+ prec_name[3]=quad
+ prec_flags[0]=--enable-single
+ prec_flags[1]=--enable-double
+ prec_flags[2]=--enable-long-double
+ prec_flags[3]=--enable-quad-precision
+ (( i=0 ))
+ (( i<2 ))
+ prec_flags[i]+=' --enable-sse2 --enable-avx'
+ (( i++ ))
+ (( i<2 ))
+ prec_flags[i]+=' --enable-sse2 --enable-avx'
+ (( i++ ))
+ (( i<2 ))
+ (( iprec=0 ))
+ (( iprec<4 ))
+ mkdir single
+ cd single
+ ln -s ../configure .
+ CFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
+ CXXFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
+ FFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
+ FCFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin'
+ CC=/usr/bin/gcc
+ CXX=/usr/bin/g++
+ FC=/usr/bin/gfortran
+ AR=/usr/bin/gcc-ar
+ NM=/usr/bin/gcc-nm
+ RANLIB=/usr/bin/gcc-ranlib
+ export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --disable-silent-rules --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --runstatedir=/run --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads --enable-openmp --enable-single --enable-sse2 --enable-avx
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-redhat-linux-gnu
checking host system type... x86_64-redhat-linux-gnu
checking for x86_64-redhat-linux-gnu-gcc... /usr/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to enable C11 features... none needed
checking whether /usr/bin/gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /usr/bin/gcc... none
checking for C compiler vendor... gnu
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by /usr/bin/gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/gcc-nm
checking the name lister (/usr/bin/gcc-nm) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-redhat-linux-gnu file names to x86_64-redhat-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-redhat-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for x86_64-redhat-linux-gnu-objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-redhat-linux-gnu-dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-redhat-linux-gnu-ar... /usr/bin/gcc-ar
checking for archiver @FILE support... @
checking for x86_64-redhat-linux-gnu-strip... no
checking for strip... strip
checking for x86_64-redhat-linux-gnu-ranlib... /usr/bin/gcc-ranlib
checking command to parse /usr/bin/gcc-nm output from /usr/bin/gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for x86_64-redhat-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for sys/time.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/gcc supports -fno-rtti -fno-exceptions... no
checking for /usr/bin/gcc option to produce PIC... -fPIC -DPIC
checking if /usr/bin/gcc PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/gcc static flag -static works... no
checking if /usr/bin/gcc supports -c -o file.o... yes
checking if /usr/bin/gcc supports -c -o file.o... (cached) yes
checking whether the /usr/bin/gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for x86_64-redhat-linux-gnu-ranlib... (cached) /usr/bin/gcc-ranlib
checking for ocamlbuild... no
checking whether C compiler accepts -mtune=native... yes
checking whether C compiler accepts -malign-double... yes
checking whether C compiler accepts -fstrict-aliasing... yes
checking whether C compiler accepts -fno-schedule-insns... yes
checking whether C compiler accepts -O3 -fomit-frame-pointer -mtune=native -malign-double -fstrict-aliasing -fno-schedule-insns... yes
checking whether C compiler accepts -msse... yes
checking whether C compiler accepts -mavx... yes
checking for egrep... (cached) /usr/bin/grep -E
checking for fcntl.h... yes
checking for fenv.h... yes
checking for limits.h... yes
checking for malloc.h... yes
checking for stddef.h... yes
checking for sys/time.h... (cached) yes
checking for altivec.h... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for long double... yes
checking for hrtime_t... no
checking size of int... 0
checking size of unsigned int... 0
checking size of long... 0
checking size of unsigned long... 0
checking size of long long... 0
checking size of unsigned long long... 0
checking size of size_t... configure: error: in `/home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/single':
configure: error: cannot compute sizeof (size_t)
See `config.log' for more details
```
from sample.config.log:
```console
configure:16755: checking size of size_t
configure:16761: /usr/bin/gcc -o conftest -O3 -fomit-frame-pointer -mtune=native -malign-double -fstrict-aliasing -fno-schedule-insns  -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin conftest.c  >&5
/usr/bin/ld: /tmp/cc9YFSzJ.lto.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
configure:16761: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "fftw"
| #define PACKAGE_TARNAME "fftw"
| #define PACKAGE_VERSION "3.3.10"
| #define PACKAGE_STRING "fftw 3.3.10"
| #define PACKAGE_BUGREPORT "fftw@fftw.org"
| #define PACKAGE_URL ""
| #define PACKAGE "fftw"
| #define VERSION "3.3.10"
| #define FFTW_ENABLE_ALLOCA 1
| #define FFTW_SINGLE 1
| #define BENCHFFT_SINGLE 1
| #define HAVE_SSE2 1
| #define HAVE_AVX 1
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_SYS_TIME_H 1
| #define STDC_HEADERS 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_FCNTL_H 1
| #define HAVE_FENV_H 1
| #define HAVE_LIMITS_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_STDDEF_H 1
| #define HAVE_SYS_TIME_H 1
| #define TIME_WITH_SYS_TIME 1
| #define HAVE_LONG_DOUBLE 1
| #define SIZEOF_INT 0
| #define SIZEOF_UNSIGNED_INT 0
| #define SIZEOF_LONG 0
| #define SIZEOF_UNSIGNED_LONG 0
| #define SIZEOF_LONG_LONG 0
| #define SIZEOF_UNSIGNED_LONG_LONG 0
| /* end confdefs.h.  */
| #include <stddef.h>
| #ifdef HAVE_STDIO_H
| # include <stdio.h>
| #endif
| #ifdef HAVE_STDLIB_H
| # include <stdlib.h>
| #endif
| #ifdef HAVE_STRING_H
| # include <string.h>
| #endif
| #ifdef HAVE_INTTYPES_H
| # include <inttypes.h>
| #endif
| #ifdef HAVE_STDINT_H
| # include <stdint.h>
| #endif
| #ifdef HAVE_STRINGS_H
| # include <strings.h>
| #endif
| #ifdef HAVE_SYS_TYPES_H
| # include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_STAT_H
| # include <sys/stat.h>
| #endif
| #ifdef HAVE_UNISTD_H
| # include <unistd.h>
| #endif
| static long int longval (void) { return (long int) (sizeof (size_t)); }
| static unsigned long int ulongval (void) { return (long int) (sizeof (size_t)); }
| #include <stdio.h>
| #include <stdlib.h>
| int
| main (void)
| {
|
|   FILE *f = fopen ("conftest.val", "w");
|   if (! f)
|     return 1;
|   if (((long int) (sizeof (size_t))) < 0)
|     {
|       long int i = longval ();
|       if (i != ((long int) (sizeof (size_t))))
|       return 1;
|       fprintf (f, "%ld", i);
|     }
|   else
|     {
|       unsigned long int i = ulongval ();
|       if (i != ((long int) (sizeof (size_t))))
|       return 1;
|       fprintf (f, "%lu", i);
|     }
|   /* Do not output a trailing newline, as this causes \r\n confusion
|      on some platforms.  */
|   return ferror (f) || fclose (f) != 0;
|
|   ;
|   return 0;
| }
configure:16766: error: in `/home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/single':
configure:16768: error: cannot compute sizeof (size_t)
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-redhat-linux-gnu
ac_cv_c_compiler_gnu=yes
ac_cv_c_const=yes
ac_cv_c_inline=inline
ac_cv_c_uint32_t=yes
ac_cv_c_uint64_t=yes
ac_cv_env_CC_set=set
ac_cv_env_CC_value=/usr/bin/gcc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_F77_set=set
ac_cv_env_F77_value=gfortran
ac_cv_env_FFLAGS_set=set
ac_cv_env_FFLAGS_value='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_MPICC_set=
ac_cv_env_MPICC_value=
ac_cv_env_build_alias_set=set
ac_cv_env_build_alias_value=x86_64-redhat-linux-gnu
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=x86_64-redhat-linux-gnu
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_header_altivec_h=no
ac_cv_header_dlfcn_h=yes
ac_cv_header_fcntl_h=yes
ac_cv_header_fenv_h=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_limits_h=yes
ac_cv_header_malloc_h=yes
ac_cv_header_stddef_h=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdio_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_time_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_unistd_h=yes
ac_cv_host=x86_64-redhat-linux-gnu
ac_cv_objext=o
ac_cv_path_EGREP='/usr/bin/grep -E'
ac_cv_path_FGREP='/usr/bin/grep -F'
ac_cv_path_GREP=/usr/bin/grep
ac_cv_path_SED=/usr/bin/sed
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_lt_DD=/usr/bin/dd
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AR=/usr/bin/gcc-ar
ac_cv_prog_AWK=gawk
ac_cv_prog_CC=/usr/bin/gcc
ac_cv_prog_DLLTOOL=dlltool
ac_cv_prog_OBJDUMP=objdump
ac_cv_prog_RANLIB=/usr/bin/gcc-ranlib
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_cc_c11=
ac_cv_prog_cc_g=yes
ac_cv_prog_cc_stdc=
ac_cv_prog_make_make_set=yes
ac_cv_sizeof_int=0
ac_cv_sizeof_long=0
ac_cv_sizeof_long_long=0
ac_cv_sizeof_unsigned_int=0
ac_cv_sizeof_unsigned_long=0
ac_cv_sizeof_unsigned_long_long=0
ac_cv_type_hrtime_t=no
ac_cv_type_long_double=yes
ac_cv_type_size_t=yes
am_cv_CC_dependencies_compiler_type=none
am_cv_make_support_nested_variables=yes
am_cv_prog_cc_c_o=yes
ax_cv_c_compiler_vendor=gnu
ax_cv_c_flags__O3__fomit_frame_pointer__mtune_native__malign_double__fstrict_aliasing__fno_schedule_insns=yes
ax_cv_c_flags__fno_schedule_insns=yes
ax_cv_c_flags__fstrict_aliasing=yes
ax_cv_c_flags__malign_double=yes
ax_cv_c_flags__mavx=yes
ax_cv_c_flags__msse=yes
ax_cv_c_flags__mtune_native=yes
lt_cv_ar_at_file=@
lt_cv_archive_cmds_need_lc=no
lt_cv_deplibs_check_method=pass_all
lt_cv_file_magic_cmd='$MAGIC_CMD'
lt_cv_file_magic_test_file=
lt_cv_ld_reload_flag=-r
lt_cv_nm_interface='BSD nm'
lt_cv_objdir=.libs
lt_cv_path_LD=/usr/bin/ld
lt_cv_path_NM=/usr/bin/gcc-nm
lt_cv_path_mainfest_tool=no
lt_cv_prog_compiler_c_o=yes
lt_cv_prog_compiler_pic='-fPIC -DPIC'
lt_cv_prog_compiler_pic_works=yes
lt_cv_prog_compiler_rtti_exceptions=no
lt_cv_prog_compiler_static_works=no
lt_cv_prog_gnu_ld=yes
lt_cv_sharedlib_from_linklib_cmd='printf %s\n'
lt_cv_shlibpath_overrides_runpath=yes
lt_cv_sys_global_symbol_pipe='sed -n -e '\''s/^.*[       ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[         ][      ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p'\'' | sed '\''/ __gnu_lto/d'\'''
lt_cv_sys_global_symbol_to_c_name_address='sed -n -e '\''s/^: \(.*\) .*$/  {"\1", (void *) 0},/p'\'' -e '\''s/^[ABCDGIRSTW][ABCDGIRSTW]* .* \(.*\)$/  {"\1", (void *) \&\1},/p'\'''
lt_cv_sys_global_symbol_to_c_name_address_lib_prefix='sed -n -e '\''s/^: \(.*\) .*$/  {"\1", (void *) 0},/p'\'' -e '\''s/^[ABCDGIRSTW][ABCDGIRSTW]* .* \(lib.*\)$/  {"\1", (void *) \&\1},/p'\'' -e '\''s/^[ABCDGIRSTW][ABCDGIRSTW]* .* \(.*\)$/  {"lib\1", (void *) \&\1},/p'\'''
lt_cv_sys_global_symbol_to_cdecl='sed -n -e '\''s/^T .* \(.*\)$/extern int \1();/p'\'' -e '\''s/^[ABCDGIRSTW][ABCDGIRSTW]* .* \(.*\)$/extern char \1;/p'\'''
lt_cv_sys_global_symbol_to_import=
lt_cv_sys_max_cmd_len=1572864
lt_cv_to_host_file_cmd=func_convert_file_noop
lt_cv_to_tool_file_cmd=func_convert_file_noop
lt_cv_truncate_bin='/usr/bin/dd bs=4096 count=1'

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} '\''/home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/missing'\'' aclocal-1.16'
ALLOCA=''
ALTIVEC_CFLAGS=''
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE='#'
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR='/usr/bin/gcc-ar'
AS='as'
AUTOCONF='${SHELL} '\''/home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/missing'\'' autoconf'
AUTOHEADER='${SHELL} '\''/home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/missing'\'' autoheader'
AUTOMAKE='${SHELL} '\''/home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/missing'\'' automake-1.16'
AVX2_CFLAGS=''
AVX512_CFLAGS=''
AVX_128_FMA_CFLAGS=''
AVX_CFLAGS='-mavx'
AWK='gawk'
BUILD_DOC_FALSE='#'
BUILD_DOC_TRUE=''
CC='/usr/bin/gcc'
CCDEPMODE='depmode=none'
CFLAGS='-O3 -fomit-frame-pointer -mtune=native -malign-double -fstrict-aliasing -fno-schedule-insns'
CHECK_PL_OPTS=''
COMBINED_THREADS_FALSE=''
COMBINED_THREADS_TRUE=''
CPP=''
CPPFLAGS=''
CSCOPE='cscope'
CTAGS='ctags'
CYGPATH_W='echo'
C_FFTW_R2R_KIND=''
C_MPI_FINT=''
DEFS=''
DEPDIR='.deps'
DLLTOOL='dlltool'
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/usr/bin/grep -E'
ETAGS='etags'
EXEEXT=''
F77='gfortran'
FFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
FGREP='/usr/bin/grep -F'
FLIBS=''
GREP='/usr/bin/grep'
HAVE_ALTIVEC_FALSE=''
HAVE_ALTIVEC_TRUE='#'
HAVE_AVX2_FALSE=''
HAVE_AVX2_TRUE='#'
HAVE_AVX512_FALSE=''
HAVE_AVX512_TRUE='#'
HAVE_AVX_128_FMA_FALSE=''
HAVE_AVX_128_FMA_TRUE='#'
HAVE_AVX_FALSE='#'
HAVE_AVX_TRUE=''
HAVE_GENERIC_SIMD128_FALSE=''
HAVE_GENERIC_SIMD128_TRUE='#'
HAVE_GENERIC_SIMD256_FALSE=''
HAVE_GENERIC_SIMD256_TRUE='#'
HAVE_KCVI_FALSE=''
HAVE_KCVI_TRUE='#'
HAVE_NEON_FALSE=''
HAVE_NEON_TRUE='#'
HAVE_SSE2_FALSE='#'
HAVE_SSE2_TRUE=''
HAVE_VSX_FALSE=''
HAVE_VSX_TRUE='#'
INDENT=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
KCVI_CFLAGS=''
LD='/usr/bin/ld -m elf_x86_64'
LDFLAGS='-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin'
LDOUBLE_FALSE=''
LDOUBLE_TRUE='#'
LIBOBJS=''
LIBQUADMATH=''
LIBS=''
LIBTOOL='$(SHELL) $(top_builddir)/libtool'
LIPO=''
LN_S='ln -s'
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} '\''/home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/missing'\'' makeinfo'
MANIFEST_TOOL=':'
MKDIR_P='/usr/bin/mkdir -p'
MPICC=''
MPILIBS=''
MPIRUN=''
MPI_FALSE=''
MPI_TRUE='#'
NEON_CFLAGS=''
NM='/usr/bin/gcc-nm'
NMEDIT=''
OBJDUMP='objdump'
OBJEXT='o'
OCAMLBUILD=''
OPENMP_CFLAGS=''
OPENMP_FALSE=''
OPENMP_TRUE=''
OTOOL64=''
OTOOL=''
PACKAGE='fftw'
PACKAGE_BUGREPORT='fftw@fftw.org'
PACKAGE_NAME='fftw'
PACKAGE_STRING='fftw 3.3.10'
PACKAGE_TARNAME='fftw'
PACKAGE_URL=''
PACKAGE_VERSION='3.3.10'
PATH_SEPARATOR=':'
POW_LIB=''
PRECISION='s'
PREC_SUFFIX='f'
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
QUAD_FALSE=''
QUAD_TRUE='#'
RANLIB='/usr/bin/gcc-ranlib'
SED='/usr/bin/sed'
SET_MAKE=''
SHARED_VERSION_INFO='9:10:6'
SHELL='/bin/sh'
SINGLE_FALSE='#'
SINGLE_TRUE=''
SMP_FALSE=''
SMP_TRUE=''
SSE2_CFLAGS='-msse'
STACK_ALIGN_CFLAGS=''
STRIP='strip'
THREADLIBS=''
THREADS_FALSE=''
THREADS_TRUE=''
VERSION='3.3.10'
VSX_CFLAGS=''
ac_ct_AR=''
ac_ct_CC=''
ac_ct_DUMPBIN=''
ac_ct_F77=''
acx_pthread_config=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE='#'
am__include='include'
am__isrc=' -I$(srcdir)'
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='/usr/bin'
build='x86_64-redhat-linux-gnu'
build_alias='x86_64-redhat-linux-gnu'
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='redhat'
datadir='/usr/share'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='/usr'
host='x86_64-redhat-linux-gnu'
host_alias='x86_64-redhat-linux-gnu'
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='redhat'
htmldir='${docdir}'
includedir='/usr/include'
infodir='/usr/share/info'
install_sh='${SHELL} /home/tkloczko/rpmbuild/BUILD/fftw-3.3.10/install-sh'
libdir='/usr/lib64'
libexecdir='/usr/libexec'
localedir='${datarootdir}/locale'
localstatedir='/var'
mandir='/usr/share/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr'
program_transform_name='s&^&&'
psdir='${docdir}'
runstatedir='/run'
sbindir='/usr/sbin'
sharedstatedir='/var/lib'
sysconfdir='/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "fftw"
#define PACKAGE_TARNAME "fftw"
#define PACKAGE_VERSION "3.3.10"
#define PACKAGE_STRING "fftw 3.3.10"
#define PACKAGE_BUGREPORT "fftw@fftw.org"
#define PACKAGE_URL ""
#define PACKAGE "fftw"
#define VERSION "3.3.10"
#define FFTW_ENABLE_ALLOCA 1
#define FFTW_SINGLE 1
#define BENCHFFT_SINGLE 1
#define HAVE_SSE2 1
#define HAVE_AVX 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_TIME_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_FCNTL_H 1
#define HAVE_FENV_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_STDDEF_H 1
#define HAVE_SYS_TIME_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_LONG_DOUBLE 1
#define SIZEOF_INT 0
#define SIZEOF_UNSIGNED_INT 0
#define SIZEOF_LONG 0
#define SIZEOF_UNSIGNED_LONG 0
#define SIZEOF_LONG_LONG 0
#define SIZEOF_UNSIGNED_LONG_LONG 0

configure: exit 77
```

If you want I can submit patch for ac 2.71 warnings (that patch will be backward compatible with older ac).

**Comment by stevengj** [comment]
I think this is the problem:
```
CPP=''
```
I noticed something similar recently; should hopefully be fixed by 80f5c5cf2a74835d101c38c54001a54de815c956

**Comment by sevan** [comment]
Hit this issue with fftw 3.3.10, so I added the new macro you added in the commit above, and ran `autoreconf`, issue is still there.

With a simple testcase `configure.ac` consisting of
```
AC_INIT
AC_CHECK_SIZEOF(int)
AC_CHECK_SIZEOF(unsigned int)
AC_CHECK_SIZEOF(long)
AC_CHECK_SIZEOF(unsigned long)
AC_CHECK_SIZEOF(long long)
AC_CHECK_SIZEOF(unsigned long long)
AC_CHECK_SIZEOF(size_t)
```
The generated `configure` script is able to work out the sizes of everything.
